Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"

	config.vm.define "router" do |router|
  		router.vm.hostname = "router"
		config.vm.provision :shell, path: "bootstrapRouter.sh"
		router.vm.network "private_network", ip: "192.168.2.2"
		router.vm.network "private_network", ip: "192.168.3.2"
		
	end

	config.vm.define "nodo1" do |nodo1|
                nodo1.vm.hostname = "nodo1"
		config.vm.provision :shell, path: "bootstrap.sh"
                nodo1.vm.network "private_network", ip: "192.168.2.3"
        end

	config.vm.define "nodo2" do |nodo2|
                nodo2.vm.hostname = "nodo2"
		config.vm.provision :shell, path: "bootstrap.sh"
                nodo2.vm.network "private_network", ip: "192.168.2.4"
        end
	 config.vm.define "nodo3" do |nodo3|
                nodo3.vm.hostname = "nodo3"
		config.vm.provision :shell, path: "bootstrap.sh"
                nodo3.vm.network "private_network", ip: "192.168.3.3"
        end
	 config.vm.define "nodo4" do |nodo4|
                nodo4.vm.hostname = "nodo4"
                config.vm.provision :shell, path: "bootstrap.sh"
                nodo4.vm.network "private_network", ip: "192.168.3.4"
        end
end
