Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"

	config.vm.define "router" do |master|
  		master.vm.hostname = "master"
		config.vm.provision :shell, path: "provision.sh"
		master.vm.network "private_network", ip: "192.168.101.2"
		
	end

	config.vm.define "nodo1" do |nodo1|
                nodo1.vm.hostname = "nodo1"
		config.vm.provision :shell, path: "provision.sh"
                nodo1.vm.network "private_network", ip: "192.168.101.3"
        end

	config.vm.define "nodo2" do |nodo2|
                nodo2.vm.hostname = "nodo2"
		config.vm.provision :shell, path: "provision.sh"
                nodo2.vm.network "private_network", ip: "192.168.101.4"
        end
	 config.vm.define "nodo3" do |nodo3|
                nodo3.vm.hostname = "nodo3"
		config.vm.provision :shell, path: "provision.sh"
                nodo3.vm.network "private_network", ip: "192.168.101.5"
        end
end
