Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"

	config.vm.define "vm1" do |vm1|
  		vm1.vm.hostname = "vm1"
		config.vm.provision :shell, path: "bootstrap.sh"
		vm1.vm.network "private_network", ip: "192.168.100.10"
	end

	config.vm.define "vm2" do |vm2|
                vm2.vm.hostname = "vm2"
		config.vm.provision :shell, path: "bootstrap.sh"
                vm2.vm.network "private_network", ip: "192.168.100.20"
        end

	config.vm.define "vm3" do |vm3|
                vm3.vm.hostname = "vm3"
		config.vm.provision :shell, path: "bootstrap.sh"
                vm3.vm.network "private_network", ip: "192.168.100.30"
        end
end
