Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/bionic64"

	config.vm.define "router" do |router|
  		router.vm.hostname = "router"
		config.vm.provision :shell, path: "bootstrapRouter.sh"
		router.vm.network "private_network", ip: "192.168.2.2"
		router.vm.network "private_network", ip: "192.168.3.2"
		
	end

	config.vm.define "vm1" do |vm1|
                vm1.vm.hostname = "vm1"
                vm1.vm.network "private_network", ip: "192.168.2.3"
        end

	config.vm.define "vm2" do |vm2|
                vm2.vm.hostname = "vm2"
                vm2.vm.network "private_network", ip: "192.168.2.4"
        end
	 config.vm.define "vm3" do |vm3|
                vm3.vm.hostname = "vm3"
                vm3.vm.network "private_network", ip: "192.168.3.3"
        end
	 config.vm.define "vm4" do |vm4|
                vm4.vm.hostname = "vm4"
                vm4.vm.network "private_network", ip: "192.168.3.4"
        end
end
